version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./shiro.ini:/app/shiro.ini:rw
      - ./logs:/app/logs:rw
    restart: always
    environment:
      - FLASK_ENV=production